name: app-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
      	SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}      	
    - uses: actions/setup-node@v1
      with:
        node-version: 16
        cache: 'npm'
    - run: make setup
    - run: make lint
    - run: make test
